### ISSUE TITLE
Responsive using root font-size

### ISSUE THREAD

**Issue by siiiick** [jongacnik/gr8#16]
Maybe something like

```javascript
var css = gr8({
  responsiveRoot: true,
  rootSizes: {
    xl: '250%',
    lg: '200%',
    md: '100%',
    sm: '62.5%'
  }
})
```

Which would return 

```css
@media (max-width: 1439px) {
  html{font-size: 250%}
}

@media (max-width: 1260px) {
  html{font-size: 200%}
}

@media (max-width: 1023px) {
  html{font-size: 100%}
}

@media (max-width: 767px) {
  html{font-size: 62.5%}
}
```
