### ISSUE TITLE
Per breakpoint values

### ISSUE THREAD

**Issue by jongacnik** [jongacnik/gr8#24]
An idea been toying with is per-breakpoint values. This could be handy when doing something like font sizes for a site. Not sure if this would be a convoluted addition or not, conceptually goes against single purpose classes a bit... pseudo code:

```js
fontSize = {
  1: {
    *: 6,
    md: 5,
    lg: 4
  },
  2: {
    *: 3,
    md: 2,
    lg: 1
  }
}
```

```css
.fs1 { font-size: 6rem }
.fs2 { font-size: 3rem }

@media (min-width: 1024px) {
  .fs1 { font-size: 5rem }
  .fs2 { font-size: 2rem }
}

@media (min-width: 1280px) {
  .fs1 { font-size: 4rem }
  .fs2 { font-size: 1rem }
}
```
